services:
  ghost:
    image: ghost:latest
    container_name: ghost
    networks:
      - traefik-vnet
    labels:
      - traefik.enable=true
      - traefik.http.routers.ghost-https.tls=true
      - traefik.http.routers.ghost-https.tls.certresolver=cloudflare
      - traefik.http.routers.ghost-https.entrypoints=websecure
      - traefik.http.routers.ghost-https.rule=Host(`enrico.es`) || Host(`www.enrico.es`)
    restart: unless-stopped
    env_file:
      - .env
    environment:
      database__client: mysql
      database__connection__host: mysql
      database__connection__database: ghost-prod
      database__connection__user: mysqldbuser_ghost
      database__connection__password: "${MYSQL_PASSWORD}"
      url: https://enrico.es
    volumes:
      - ./data:/var/lib/ghost/content:rw
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: mysql
    networks:
      - traefik-vnet
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ghost-prod
      MYSQL_USER: mysqldbuser_ghost
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
      - ./ghost-db:/var/lib/mysql:rw
networks:
  traefik-vnet:
    external: true
